

name: farm_direct
description: A new Flutter project.

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  provider: ^6.1.2 # Updated version
fl_chart: ^0.40.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true